# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecomparision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_upload',
            old_name='file_field',
            new_name='file_field_1',
        ),
        migrations.AddField(
            model_name='file_upload',
            name='file_field_2',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
