# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filecomparision', '0002_auto_20180223_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_upload',
            old_name='file_field_1',
            new_name='file_1',
        ),
        migrations.RenameField(
            model_name='file_upload',
            old_name='file_field_2',
            new_name='file_2',
        ),
    ]
